### ISSUE TITLE
I would like to port this example to Micronaut guides

### ISSUE THREAD

**Issue by sdelamo** [jobrunr/example-micronaut#2]
Hi, I would like to port this example to [Micronaut Guides](https://guides.mcironaut.io) which repository is in [https://github.com/micronaut-projects/micronaut-guides](https://github.com/micronaut-projects/micronaut-guides). 
Are you ok if I do that?

**Comment by rdehuyss** [comment]
Hey @sdelamo - I'm really sorry to only answer now. I do not have notifications enabled for the example projects to be honest. But, feel free to port this project to micronaut-guides. I would be honoured.
